config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Home route: redirects to login or photos
  root to: 'home#index'

  # Instagram Auth Routes
  get '/auth/instagram', to: 'instagram_auth#authorize', as: 'instagram_auth'
  get '/auth/instagram/callback', to: 'instagram_auth#callback'

  # Google One-tap Auth Route
  post '/auth/google/callback', to: 'google_auth#callback'

  get '/connect', to: 'welcome#connect'
  get '/reconnect', to: 'welcome#reconnect'
  get '/loading', to: 'welcome#loading'

  resources :photos, only: %i[index show]
  get '/photos/:photo_id/new', to: 'builder#new', as: 'build_new'

  get '/sender/:id/preview', to: 'builder#preview', as: 'build_preview'
  get '/sender/:id/caption', to: 'builder#caption', as: 'build_caption'
  get '/sender/:id/recipients', to: 'builder#recipients', as: 'build_recipients'
  get '/sender/:id/address', to: 'builder#recipient', as: 'build_new_recipient'
  get '/sender/:id/payment', to: 'builder#payment', as: 'build_payment'
  get '/sender/:id/success', to: 'builder#success', as: 'build_success'

  patch '/sender/:id/caption', to: 'builder#update_caption', as: 'update_caption'
  patch '/sender/:id/address', to: 'builder#create_recipient', as: 'create_recipient'
  patch '/sender/:id/recipients', to: 'builder#update_recipients', as: 'update_recipients'
  patch '/sender/:id/payment', to: 'builder#update_payment', as: 'update_payment'

  get '/postcards', to: 'orders#index', as: :orders
  get '/postcards/:id', to: 'orders#show', as: :order

  resources :recipients, except: %i[show]

  namespace :api do
    resources :photos, only: %i[create]
  end

  mount ActionCable.server => '/cable'

  # Static routes
  get '/privacy' => 'static#privacy'
  get '/terms' => 'static#terms'

  # Webhooks
  post '/lob' => 'lob_webhook#webhook'

  # Development only routes
  if Rails.env.development?
    get '/template/back', to: 'postcard_template#back'
    get '/template/front', to: 'postcard_template#front'
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/:slug' => 'posts#show'
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos, dependent: :destroy
  has_many :recipients, dependent: :destroy
  has_many :postcards, through: :photos
  has_many :orders, through: :photos

  before_validation :generate_password

  after_create :send_welcome_email

  def instagram?
    instagram_uid.present?
  end

  def stripe_customer
    @stripe_customer ||=
      payment_customer_id ? retrieve_stripe_customer : create_stripe_customer
  end

  def add_default_stripe_source(source)
    customer = Stripe::Customer.update(
      stripe_customer.id,
      source: source
    )
    @stripe_customer = customer
  end

  def email_required?
    false
  end

  private

  def create_stripe_customer
    customer = Stripe::Customer.create(
      email: email,
      name: ig_username
    )

    update(payment_customer_id: customer.id)
    customer
  end

  def retrieve_stripe_customer
    Stripe::Customer.retrieve(payment_customer_id)
  end

  def send_welcome_email
    return if email.blank?

    UserMailer.with(user: self).welcome_email.deliver_later
  end

  def generate_password
    return if password.present? || !new_record?

    self.password = Devise.friendly_token
  end
end

app/controllers/builder_controller.rb
class BuilderController < ApplicationController
  attr_reader :order

  before_action :authenticate_user!
  before_action :set_order, except: :new

  STRIPE_CHARGE_DESCRIPTION = 'GramGram Photo'.freeze
  USER_PARAMS = %i[name email].freeze
  RECIPIENT_PARAMS = %i[
    name
    address_line1
    address_line2
    address_city
    address_state
    address_zip
  ].freeze

  def new
    photo = current_user.photos.find(params[:photo_id])
    order = Order.create(photo: photo)

    if current_user.recipients.empty?
      return redirect_to build_new_recipient_path(order)
    end

    if current_user.recipients.length == 1
      order.recipients << current_user.recipients.first
    end

    redirect_to build_recipients_path(order)
  end

  def new_recipient
    @recipient = current_user.recipients.new
  end

  def recipients
    @recipients = current_user.recipients.order(:name)
  end

  def create_recipient
    @recipient = current_user.recipients.new(recipient_params)
    order.recipients << @recipient

    if @recipient.save && order.save
      redirect_to build_recipients_path
    else
      render 'recipient'
    end
  end

  def update_recipients
    recipient_ids = params.require(:order)[:recipient_ids]
    recipients = current_user.recipients.where(id: recipient_ids)
    order.recipients = recipients

    if order.save && order.recipients.count > 0
      redirect_to build_caption_path
    else
      @recipients = current_user.recipients.order(:name)
      render 'recipients'
    end
  end

  def update_caption
    if order.update(caption_params)
      redirect_to build_payment_path
    else
      render 'caption'
    end
  end

  def update_payment
    current_user.update(email: email) if email
    current_user.add_default_stripe_source(token) if token

    charge = process_stripe_charge
    if charge && order.update(stripe_charge_id: charge[:id])
      redirect_to build_success_path
    else
      render 'payment'
    end
  rescue Stripe::CardError => e
    @card_error = e
    render 'payment'
  end

  private

  def set_order
    @order = current_user.orders.find(params[:id])
  end

  def user_params
    params.permit(USER_PARAMS)
  end

  def recipient_params
    params.require(:recipient).permit(RECIPIENT_PARAMS)
  end

  def caption_params
    params.require(:order).permit(:caption)
  end

  def process_stripe_charge
    opts = {
      amount: order.price_in_cents,
      currency: 'usd',
      description: STRIPE_CHARGE_DESCRIPTION,
      customer: current_user.payment_customer_id,
      metadata: stripe_metadata
    }
    Stripe::Charge.create(opts, idempotency_key: order.id)
  end

  def stripe_metadata
    {
      order_id: order.id
    }
  end

  def token
    params[:token]
  end

  def email
    params[:email]
  end

  def find_or_initialize_recipient
    id = params[:recipient_id]
    return current_user.recipients.find(id) if id

    current_user.recipients.new(recipient_params)
  end
end

app/helpers/builder_helper.rb
module BuilderHelper
  def formatted_price
    Money.new(@order.price_in_cents, 'USD').format
  end

  def postcard_count
    @postcard_count ||= @order.recipients.count
  end

  def default_payment_source
    id = @current_user.stripe_customer.default_source
    payment_sources.find { |x| x.id == id }
  end

  def payment_sources
    @current_user.stripe_customer.sources
  end

  def exp_date
    source = default_payment_source
    "#{source.exp_month}/#{source.exp_year}"
  end
end

app/views/builder/_mobile-nav.html.erb
<!-- Header nav with back button -->
<nav class="d-md-none navbar fixed-top navbar-light bg-primary">
  <%= link_to photos_path, class: 'nav-link text-dark' do %>
    Cancel
  <% end %>

  <button type="submit" class="btn btn-dark btn-spinner btn-sm">
    Next
  </button>
</nav>

app/views/builder/_payment-form.html.erb
<% if default_payment_source %>
  <div class="form-group">
    <label class="form-control-label">Credit or Debit Card</label>

    <div class="text-muted">
      <%= default_payment_source.brand %>
      <div class="float-md-right">
        ●●●●
        <%= default_payment_source.last4 %>
      </div>
    </div>
    <small class="text-muted">Expires: <%= exp_date %></small>
  </div>
<% else %>

  <div class="form-group card-input-group">
    <label class="form-control-label">Credit or Debit Card</label>

    <div class="credit-card-input form-control">
    </div>
    <div class="invalid-feedback <%= @card_error ? 'd-block' : '' %>">
      <% if @card_error %>
        <%= @card_error.message %>
      <% end %>
    </div>
  </div>

  <%= hidden_field_tag(:token, '', class: 'stripe-token-input') %>
<% end %>

app/views/builder/_save-btn.html.erb
<button type="submit" class="d-none d-md-block mt-5 mb-2 btn btn-block btn-outline-dark btn-spinner">
  Next
  <span class="iconify ml-1 mb-1" data-icon="ion:arrow-forward" data-inline="false"></span>
</button>

app/views/builder/caption.html.erb
<% content_for :title, 'Add a Caption' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100">
  <%= form_with model: @order, url: update_caption_path(@order), local: true do |f| %>

    <%= render 'mobile-nav' %>

    <div class="container skinny-container py-5">
      <div class="shadow mt-4 p-2">
        <%= image_tag(@order.photo.img_src, class: 'img rounded w-100') %>

        <%= f.text_area :caption, class: 'bg-white form-control caption-input', maxlength: 200, cols: 30, rows: 7, placeholder: 'Add a caption' %>

        <div class="text-right">
          <small class="form-text text-muted caption-input-msg"></small>
        </div>
      </div>

      <%= render 'save-btn' %>
    </div>
  <% end %>
</div>

app/views/builder/payment.html.erb
<% content_for :title, 'Send the Postcard' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100">
  <%= form_with model: @current_user, method: :patch, url: update_payment_path(@order), class: 'p-4 p-md-5 payment-form' do |form| %>

    <%= render 'shared/mobile-nav' do %>
      <%= link_to photos_path, class: 'nav-link text-dark' do %>
        Cancel
      <% end %>

      <button type="submit" class="btn btn-dark btn-spinner btn-sm">
        Pay <%= formatted_price %>
      </button>
    <% end %>

    <div class="container skinny-container py-5">
      <p class="mb-4">
        Almost done!
      </p>

      <table class="table table-sm table-borderless w-100 mb-5">
        <tbody>
          <tr>
            <td>
              <div class="d-flex align-items-start mb-4">
                <%= image_tag(@order.photo.img_src, class: 'img rounded w-60') %>
                <div class="ml-2">
                  <%= postcard_count %> x Postcard
                  <div class="text-muted">
                    <small>
                      $2.95 / postcard
                    </small>
                  </div>
                </div>
              </div>
            </td>
            <td class="text-right"><%= formatted_price %></td>
          </tr>
          <tr class="border-top mb-4">
            <td class="my-4"></td>
            <td class="my-4"></td>
          </tr>
          <tr>
            <td>Tax</td>
            <td class="text-right">$0.00</td>
          </tr>
          <tr>
            <td>
              Total
            </td>
            <td class="text-right">
              <%= formatted_price %>
            </td>
          </tr>
        </tbody>
      </table>

      <% if @current_user.email.blank? %>
        <div class="form-group mb-4">
          <label class="form-control-label">Email Address</label>

          <%= form.email_field :email, class: 'form-control', placeholder: 'Email Address', autofocus: true, autocomplete: "email", required: true %>
        </div>
      <% end %>

      <%= render 'payment-form' %>

      <button type="submit" class="d-none d-md-block mt-5 mb-2 btn btn-block btn-outline-dark btn-spinner">
        Pay <%= formatted_price %>
      </button>

      <p class="mt-5 text-muted text-center">
        <small>
          <span class="iconify" data-icon="bx:bxs-lock" data-inline="false"></span>
          Powered by <a class="text-muted" href="https://stripe.com">Stripe</a>
        </small>
      </p>
    </div>
  <% end %>
</div>

app/views/builder/preview.html.erb
<% content_for :title, 'Preview Post' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100">
  <%= render 'shared/mobile-nav' do %>
    <%= link_to photos_path, class: 'nav-link text-dark pl-0' do %>
      Cancel
    <% end %>

    <button type="submit" class="btn btn-dark btn-spinner btn-sm">
      Next
    </button>
  <% end %>

  <div class="container skinny-container py-5">
    <p class="pt-4 mb-4">
      Where do you want us to send the&nbsp;photo?
    </p>

    <%= render 'shared/postcard-preview', postcard: @postcard %>
  </div>
</div>

app/views/builder/recipient.html.erb
<% content_for :title, 'Add a Recipient' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100">
  <%= form_with model: @order, class: 'p-4', url: create_recipient_path(@order), local: true do |form| %>
    <%= render 'mobile-nav' %>

    <div class="container skinny-container py-5">
      <p class="mb-4">
        Where do you want us to send the&nbsp;postcard?
      </p>


      <%= fields_for :recipient, @recipient do |recipient| %>
        <%= render 'recipients/form-fields', form: recipient %>
      <% end %>

      <%= render 'save-btn' %>
    </div>
  <% end %>
</div>

app/views/builder/recipients.html.erb
<% content_for :title, 'Pick a Recipient' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100">
  <%= form_with model: @order, class: 'p-4', url: update_recipients_path(@order), local: true do |form| %>
    <%= render 'mobile-nav' %>

    <div class="container skinny-container py-5">
      <p class="mb-4">
        Where do you want us to send the&nbsp;postcard?
      </p>

      <% @recipients.each do |recipient| %>
        <div class="custom-control custom-checkbox mr-sm-2">
          <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
          <%= form.check_box(:recipient_ids, { class: 'custom-control-input', id: recipient.id, multiple: true, checked: @order.recipients.include?(recipient) }, recipient.id, nil) %>
          <label class="custom-control-label" for="<%= recipient.id %>">
            <h5 class="mb-0"><%= recipient.name %></h5>
            <p class="text-muted">
              <%= recipient.address_line1 %> <%= recipient.address_line2 %>
              <br/>
              <%= recipient.address_city %>, <%= recipient.address_state %> <%= recipient.address_zip %>
            </p>
          </label>
        </div>
      <% end %>

      <%= form.hidden_field :hidden %>

      <%= link_to 'Add Another', build_new_recipient_path %>

      <%= render 'save-btn' %>
    </div>
  <% end %>
</div>

app/views/builder/success.html.erb
<% content_for :title, 'Success' %>

<div class="fluid-container bg-primary vh-100">
  <!-- Header nav with back button -->
  <nav class="navbar fixed-top navbar-light">
    <a class="navbar-brand" href="/">
      <span class="iconify" data-icon="ion:arrow-back" data-inline="false"></span>
    </a>
  </nav>

  <div class="container skinny-container">
    <div class="py-5 text-center">
      <div class="circle-loader mt-5">
        <div class="success-checkmark checkmark draw"></div>
      </div>

      <h3 class="mt-4">
        Sent!
      </h3>
    </div>

    <%= link_to 'Send Another Photo', photos_path, class: 'mt-5 mb-2 btn btn-block btn-dark' %>
  </div>
</div>