config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Home route: redirects to login or photos
  root to: 'home#index'

  # Instagram Auth Routes
  get '/auth/instagram', to: 'instagram_auth#authorize', as: 'instagram_auth'
  get '/auth/instagram/callback', to: 'instagram_auth#callback'

  # Google One-tap Auth Route
  post '/auth/google/callback', to: 'google_auth#callback'

  get '/connect', to: 'welcome#connect'
  get '/reconnect', to: 'welcome#reconnect'
  get '/loading', to: 'welcome#loading'

  resources :photos, only: %i[index show]
  get '/photos/:photo_id/new', to: 'builder#new', as: 'build_new'

  get '/sender/:id/preview', to: 'builder#preview', as: 'build_preview'
  get '/sender/:id/caption', to: 'builder#caption', as: 'build_caption'
  get '/sender/:id/recipients', to: 'builder#recipients', as: 'build_recipients'
  get '/sender/:id/address', to: 'builder#recipient', as: 'build_new_recipient'
  get '/sender/:id/payment', to: 'builder#payment', as: 'build_payment'
  get '/sender/:id/success', to: 'builder#success', as: 'build_success'

  patch '/sender/:id/caption', to: 'builder#update_caption', as: 'update_caption'
  patch '/sender/:id/address', to: 'builder#create_recipient', as: 'create_recipient'
  patch '/sender/:id/recipients', to: 'builder#update_recipients', as: 'update_recipients'
  patch '/sender/:id/payment', to: 'builder#update_payment', as: 'update_payment'

  get '/postcards', to: 'orders#index', as: :orders
  get '/postcards/:id', to: 'orders#show', as: :order

  resources :recipients, except: %i[show]

  namespace :api do
    resources :photos, only: %i[create]
  end

  mount ActionCable.server => '/cable'

  # Static routes
  get '/privacy' => 'static#privacy'
  get '/terms' => 'static#terms'

  # Webhooks
  post '/lob' => 'lob_webhook#webhook'

  # Development only routes
  if Rails.env.development?
    get '/template/back', to: 'postcard_template#back'
    get '/template/front', to: 'postcard_template#front'
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/:slug' => 'posts#show'
end

app/views/shared/_banner.html.erb
<div class="fluid-container bg-primary">
  <div class="container pt-5 pb-4">
    <div class="d-flex flow-row mb-md-3">
      <div class="mr-auto">
        <h2 class="mb-0">
          <%= title %>
        </h2>
        <small class="text-muted">
          <%= small %>
        </small>
      </div>

      <div class="ml-auto d-md-none">
        <%= render 'shared/user-dropdown' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% info_msg = flash[:notice] %>
<% error_msg = flash[:alert] %>

<div class="flash-container container fixed-top mt-4">
  <% if info_msg %>
    <div class="alert alert-secondary alert-dismissible fade show" data-auto-hide="true" role="alert">
      <%= info_msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% if error_msg %>
    <div class="alert alert-secondary alert-dismissible fade show" data-auto-hide="true" role="alert">
      <%= error_msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="bg-white w-100">
  <div class="container">
  </div>
</div>

<footer class="footer bg-light pb-5">
  <div class="container">
    <div class="row py-5">
      <div class="col-md-6">
        <% @posts.map do |post| %>
          <div class="mb-1">
            <%= link_to post.title, post.slug, class: 'text-muted' %>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <div class="mb-1">
          <a href="/terms" target="_blank" class="text-muted">
            Terms and Conditions
          </a>
        </div>
        <div class="mb-1">
          <a href="/privacy" target="_blank" class="text-muted">
            Privacy Policy
          </a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p class="text-muted">
          © <%= copyright_year %> <%= company_name %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_google-one-tap.html.erb
<%= form_with url: auth_google_callback_path, local: true, class: 'google-onetap' do |form|  %>
  <%= form.hidden_field(:credential) %>
<% end %>

app/views/shared/_gtm.html.erb
<% gtm_id = ENV['GTM_ID'] %>

<% if gtm_id %>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<%= gtm_id %>');</script>
<!-- End Google Tag Manager -->
<% end %>

app/views/shared/_head.html.erb
<head>
  <title>
    <%= yield(:title).present? ? "#{yield(:title)} | " : '' %> GramGram
  </title>
  <%= action_cable_meta_tag %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="description" content="<%= yield(:meta_description) %>">

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#e2c0bb">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#e2c0bb">


  <meta property="og:image" content="<%= image_url('og-image.jpg') %>" />
  <meta property="og:title" content="<%= yield(:title).present? ? "#{yield(:title)} | " : '' %> GramGram" />
  <meta property="og:description" content="<%= yield(:meta_description) %>" />
  <meta property="og:url" content="<%= canonical_url %>" />

  <link rel="canonical" href="<%= canonical_url %>" />

  <%= render 'shared/gtm' %>

  <script>
   window.GOOGLE_CLIENT_ID = '<%= ENV['GOOGLE_CLIENT_ID'] %>';
   window.STRIPE_PUBLISHABLE_KEY = '<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>';
   window.MAPBOX_ACCESS_TOKEN = '<%= ENV['MAPBOX_ACCESS_TOKEN'] %>';
   window.CLOUDINARY_ENABLED = <%= ENV['CLOUDINARY_ENABLED'].present? %>;
  </script>

  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <% if ENV['BUGSNAG_PUBLIC_KEY'].present? %>
    <script src="//d2wy8f7a9ursnm.cloudfront.net/v6/bugsnag.min.js"></script>
    <script>window.bugsnagClient = bugsnag('<%= ENV['BUGSNAG_PUBLIC_KEY'] %>')</script>
  <% end %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_mobile-nav.html.erb
<!-- Header nav with back button -->
<nav class="d-md-none navbar fixed-top navbar-light bg-primary">
  <%= yield %>
</nav>

app/views/shared/_navbar.html.erb
<nav class="d-none d-md-block navbar navbar-expand-sm bg-primary navbar-light">
  <div class="container">

    <%= link_to 'GramGram', root_path, class: 'navbar-brand' %>

    <ul class="navbar-nav nav ml-auto">
      <li class="nav-item mt-2">
        <%= render 'shared/user-dropdown' %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_postcard-preview.html.erb
<div class="postcard-preview shadow">
  <!-- do not put text outside of the safe area -->
  <div class="blur" style="background-image: url(<%= order.photo_url %>)"></div>

  <%= image_tag(order.photo_url) %>
</div>

app/views/shared/_social-share.html.erb
<div class="social-share text-muted">
  <a href="https://www.facebook.com/GramGram-110906980578546" target="_blank">
    <span class="iconify" data-icon="entypo-social:facebook-with-circle" data-inline="false"></span>
  </a>

  <a href="https://twitter.com/gramgram_app" target="_blank">
    <span class="iconify" data-icon="entypo-social:twitter-with-circle" data-inline="false"></span>
  </a>

  <a href="https://www.instagram.com/gramgram.app/" target="_blank">
    <span class="iconify" data-icon="entypo-social:instagram-with-circle" data-inline="false"></span>
  </a>
</div>

app/views/shared/_user-dropdown.html.erb
<div class="dropdown">
  <a href="#" class="d-flex" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="avatar rounded-circle border border-white">
      <% if current_user.ig_avatar %>
        <%= image_tag(current_user.ig_avatar, alt: 'Avatar') %>
      <% else %>
        <span class="iconify" data-icon="whh:profile" data-inline="false"></span>
      <% end %>
    </span>

    <span class="iconify align-self-center text-dark dropdown-icon" data-icon="ic:round-arrow-drop-down" data-inline="false"></span>
  </a>

  <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
    <%= link_to 'Send a Photo', photos_path, class: 'dropdown-item' %>
    <%= link_to 'Sent Postcards', orders_path, class: 'dropdown-item' %>
    <%= link_to 'Address Book', recipients_path, class: 'dropdown-item' %>
    <%= link_to('Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item') %> 
  </div>
</div>