config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Home route: redirects to login or photos
  root to: 'home#index'

  # Instagram Auth Routes
  get '/auth/instagram', to: 'instagram_auth#authorize', as: 'instagram_auth'
  get '/auth/instagram/callback', to: 'instagram_auth#callback'

  # Google One-tap Auth Route
  post '/auth/google/callback', to: 'google_auth#callback'

  get '/connect', to: 'welcome#connect'
  get '/reconnect', to: 'welcome#reconnect'
  get '/loading', to: 'welcome#loading'

  resources :photos, only: %i[index show]
  get '/photos/:photo_id/new', to: 'builder#new', as: 'build_new'

  get '/sender/:id/preview', to: 'builder#preview', as: 'build_preview'
  get '/sender/:id/caption', to: 'builder#caption', as: 'build_caption'
  get '/sender/:id/recipients', to: 'builder#recipients', as: 'build_recipients'
  get '/sender/:id/address', to: 'builder#recipient', as: 'build_new_recipient'
  get '/sender/:id/payment', to: 'builder#payment', as: 'build_payment'
  get '/sender/:id/success', to: 'builder#success', as: 'build_success'

  patch '/sender/:id/caption', to: 'builder#update_caption', as: 'update_caption'
  patch '/sender/:id/address', to: 'builder#create_recipient', as: 'create_recipient'
  patch '/sender/:id/recipients', to: 'builder#update_recipients', as: 'update_recipients'
  patch '/sender/:id/payment', to: 'builder#update_payment', as: 'update_payment'

  get '/postcards', to: 'orders#index', as: :orders
  get '/postcards/:id', to: 'orders#show', as: :order

  resources :recipients, except: %i[show]

  namespace :api do
    resources :photos, only: %i[create]
  end

  mount ActionCable.server => '/cable'

  # Static routes
  get '/privacy' => 'static#privacy'
  get '/terms' => 'static#terms'

  # Webhooks
  post '/lob' => 'lob_webhook#webhook'

  # Development only routes
  if Rails.env.development?
    get '/template/back', to: 'postcard_template#back'
    get '/template/front', to: 'postcard_template#front'
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/:slug' => 'posts#show'
end

app/models/recipient.rb
# frozen_string_literal: true

# Someone who receives a postcard and their mailing information
class Recipient < ApplicationRecord
  has_many :postcards
  belongs_to :user

  has_and_belongs_to_many :orders

  validates_presence_of :name,
                        :address_line1,
                        :address_city,
                        :address_state,
                        :address_zip

  def self.default
    order(:created_at).last
  end

  def address
    {
      name: name,
      address_line1: address_line1,
      address_line2: address_line2,
      address_city: address_city,
      address_state: address_state,
      address_zip: address_zip
    }
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipient, only: %i[show edit update destroy]

  RECIPIENT_PARAMS = %i[
    name
    address_line1
    address_line2
    address_city
    address_state
    address_zip
  ].freeze

  def index
    @recipients = current_user.recipients
  end

  def new
    @recipient = current_user.recipients.new
  end

  def create
    @recipient = current_user.recipients.new(recipient_params)

    if @recipient.save
      redirect_to recipients_path
    else
      render 'new'
    end
  end

  def update
    if @recipient.update(recipient_params)
      redirect_to recipients_path
    else
      render 'edit'
    end
  end

  def destroy
    @recipient.destroy
  end

  private

  def recipient_params
    params.require(:recipient).permit(RECIPIENT_PARAMS)
  end

  def set_recipient
    @recipient = current_user.recipients.find(params[:id])
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/_form-fields.html.erb
<div class="form-group">
  <%= form.text_field :name, placeholder: 'Name', class: 'form-control' %>
</div>
<div class="form-group">
  <%= form.text_field :address_line1, autocomplete: 'address-search', placeholder: 'Address', class: 'form-control address-search' %>
</div>
<div class="form-group">
  <%= form.text_field :address_line2, placeholder: 'Address 2 (optional)', class: 'form-control' %>
</div>
<div class="form-row">
  <div class="form-group col-md-6">
    <%= form.text_field :address_city, placeholder: 'City', class: 'form-control address-city' %>
  </div>
  <div class="form-group col-6 col-md-3">
    <%= form.text_field :address_state, placeholder: 'State', class: 'form-control address-state' %>
  </div>
  <div class="form-group col-6 col-md-3">
    <%= form.text_field :address_zip, placeholder: 'Zip', class: 'form-control address-zip' %>
  </div>
</div>

app/views/recipients/_form.html.erb
<%= form_with model: @recipient, local: true do |form| %>
  <div class="form-group">
    <label>Name</label>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="inputAddress">Address</label>
    <%= form.text_field :address_line1, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <%= form.text_field :address_line2, class: 'form-control' %>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <%= form.text_field :address_city, class: 'form-control' %>
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <%= form.text_field :address_state, class: 'form-control' %>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <%= form.text_field :address_zip, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary btn-spinner py-3 px-5">
      Save
    </button>
  </div>
<% end %>

app/views/recipients/edit.html.erb
<% content_for :title, 'Edit Recipient' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100 p-4">
  <%= form_with model: @recipient, local: true do |form| %>
    <%= render 'shared/mobile-nav' do %>
      <%= link_to recipients_path, class: 'ml-0 nav-link text-dark' do %>
        Cancel
      <% end %>

      <button type="submit" class="btn btn-dark btn-spinner btn-sm">
        Update
      </button>
    <% end %>

    <div class="container skinny-container py-5">
      <div class="mt-4">
        <%= render 'form-fields', form: form %>
      </div>

      <button type="submit" class="d-none d-md-block mt-5 mb-2 btn btn-spinner btn-block btn-outline-dark">
        Update
      </button>
    </div>
  <% end %>
</div>

app/views/recipients/index.html.erb
<% content_for :title, 'Address Book' %>

<%= render 'shared/navbar' %>
<%= render 'shared/banner', title: 'Address Book', small: 'Probably a list of your grandmas' %>

<div class="fluid-container vh-100 bg-light">
  <div class="container pt-2 pt-md-4 pb-4">
    <% if @recipients.empty? %>
      <p class="text-muted">
        Looks like you haven't added your grandma yet!
      </p>
    <% end %>

    <% @recipients.map do |r| %>
      <%= link_to edit_recipient_path(r), class: 'text-reset' do %>
        <div class="card mb-2">
          <div class="card-body">
            <h5 class="card-title">
              <%= r.name %>
            </h5>
            <p class="card-text">
              <%= r.address_line1 %> <%= r.address_line2 %>
              <br/>
              <%= r.address_city %>, <%= r.address_state %> <%= r.address_zip %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="bg-white shadow fixed-bottom p-4 text-center">
    <div class="container skinny-container">
      <%= link_to 'Add Recipient', new_recipient_path, class: 'btn w-100 btn-outline-dark' %>
    </div>
  </div>
</div>

app/views/recipients/new.html.erb
<% content_for :title, 'Add a Recipient' %>

<%= render 'shared/navbar' %>

<div class="fluid-container vh-100 p-4">
  <%= form_with model: @recipient, local: true do |form| %>
    <%= render 'shared/mobile-nav' do %>
      <%= link_to recipients_path, class: 'ml-0 nav-link text-dark' do %>
        Cancel
      <% end %>

      <button type="submit" class="btn btn-dark btn-spinner btn-sm">
        Save
      </button>
    <% end %>

    <div class="container skinny-container py-5">
      <div class="mt-4">
        <%= render 'form-fields', form: form %>
      </div>

      <button type="submit" class="d-none d-md-block mt-5 mb-2 btn btn-spinner btn-block btn-outline-dark">
        Save
      </button>
    </div>
  <% end %>
</div>

app/views/recipients/show.html.erb
<div class="pt-5 container">
  <%= link_to 'Back', recipients_path %>
  <%= link_to 'Edit', edit_recipient_path(@recipient) %>

  <small class="text-muted">
    Name
  </small>
  <p>
    <%= @recipient.name %>
  </p>

  <small class="text-muted">Address</small>
  <p>
    <%= @recipient.address_line1 %>
    <%= @recipient.address_line2 %>
  </p>

  <div class="row">
    <div class="col-md-6">
      <small class="text-muted">City</small>
      <p><%= @recipient.address_city %></p>
    </div>
    <div class="col-md-6">
      <small class="text-muted">State</small>
      <p><%= @recipient.address_state %></p>
    </div>
  </div>

  <small class="text-muted">Zip</small>
  <p><%= @recipient.address_zip %></p>
</div>