config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Home route: redirects to login or photos
  root to: 'home#index'

  # Instagram Auth Routes
  get '/auth/instagram', to: 'instagram_auth#authorize', as: 'instagram_auth'
  get '/auth/instagram/callback', to: 'instagram_auth#callback'

  # Google One-tap Auth Route
  post '/auth/google/callback', to: 'google_auth#callback'

  get '/connect', to: 'welcome#connect'
  get '/reconnect', to: 'welcome#reconnect'
  get '/loading', to: 'welcome#loading'

  resources :photos, only: %i[index show]
  get '/photos/:photo_id/new', to: 'builder#new', as: 'build_new'

  get '/sender/:id/preview', to: 'builder#preview', as: 'build_preview'
  get '/sender/:id/caption', to: 'builder#caption', as: 'build_caption'
  get '/sender/:id/recipients', to: 'builder#recipients', as: 'build_recipients'
  get '/sender/:id/address', to: 'builder#recipient', as: 'build_new_recipient'
  get '/sender/:id/payment', to: 'builder#payment', as: 'build_payment'
  get '/sender/:id/success', to: 'builder#success', as: 'build_success'

  patch '/sender/:id/caption', to: 'builder#update_caption', as: 'update_caption'
  patch '/sender/:id/address', to: 'builder#create_recipient', as: 'create_recipient'
  patch '/sender/:id/recipients', to: 'builder#update_recipients', as: 'update_recipients'
  patch '/sender/:id/payment', to: 'builder#update_payment', as: 'update_payment'

  get '/postcards', to: 'orders#index', as: :orders
  get '/postcards/:id', to: 'orders#show', as: :order

  resources :recipients, except: %i[show]

  namespace :api do
    resources :photos, only: %i[create]
  end

  mount ActionCable.server => '/cable'

  # Static routes
  get '/privacy' => 'static#privacy'
  get '/terms' => 'static#terms'

  # Webhooks
  post '/lob' => 'lob_webhook#webhook'

  # Development only routes
  if Rails.env.development?
    get '/template/back', to: 'postcard_template#back'
    get '/template/front', to: 'postcard_template#front'
  end

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'

  get '/:slug' => 'posts#show'
end

app/models/photo.rb
# frozen_string_literal: true

# A photo that could be featured on a Postcard
class Photo < ApplicationRecord
  has_many :postcards, dependent: :destroy
  has_many :orders, dependent: :destroy
  belongs_to :user

  validates :user, presence: true
  validates :ig_id, uniqueness: { scope: :user }, if: -> { ig_id.present? }

  self.per_page = 48 # divisible by 2, 4, 6

  def img_src
    url || ig_media_url
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  respond_to :json

  def create
    respond_with current_user.photos.create(photo_params)
  end

  private

  def photo_params
    params.require(:photo).permit(:url)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :check_sync_at!, only: :index

  def index
    @photos = current_user
              .photos
              .page(params[:page])
              .order(ig_timestamp: :desc)
  end

  def show
    @photo = current_user.photos.find(params[:id])
  end

  private

  def check_sync_at!
    return if current_user.sync_at.nil? || !current_user.instagram?

    redirect_to reconnect_path if current_user.sync_at < 1.day.ago
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def lazy_image_tag(url, opts)
    opts[:class] = "#{opts[:class]} img-lazy"
    tag.img(opts.merge(data: { src: url }))
  end
end

app/views/photos/index.html.erb
<% content_for :title, 'Photos' %>

<%= render 'shared/navbar' %>
<%= render 'shared/banner', title: 'Photos', small: 'Select an image to get started' %>

<div class="container mt-2 mt-md-4 mb-5">
  <div class="row mt-2 mb-4">
    <div class="col-12">
      <% if @current_user.instagram? %>
        <%= link_to loading_path, class: 'btn btn-sm btn-outline-secondary' do %>
          <span class="iconify" data-icon="heroicons-outline:refresh" data-inline="false"></span>
          Resync Photos
        <% end %>
      <% else %>
        <%= link_to connect_path, class: 'btn btn-sm btn-outline-secondary' do %>
          <span class="iconify" data-icon="heroicons-outline:refresh" data-inline="false"></span>
          Sync with Instagram
        <% end %>
      <% end %>

      <button class="btn btn-sm btn-outline-secondary btn-upload">
        <span class="iconify" data-icon="heroicons-outline:upload" data-inline="false"></span>
        Upload Photo
      </button>
    </div>
  </div>
  <div class="photo-grid mx-n1">
    <div class="grid-sizer col-6 col-md-3 col-lg-2"></div>
    <% if @photos.empty? %>
      <p class="text-muted">
        Looks like you haven't added any photos yet!
      </p>
    <% end %>

    <% @photos.each do |p| %>
      <div class="grid-item col-6 col-md-3 col-lg-2 p-1">
        <div class="overflow-hidden rounded">
          <%= link_to(build_new_path(p), class: 'd-block') do %>
            <%= lazy_image_tag(p.img_src, class: 'img-fluid img-zoom') %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row mt-5">
    <div class="col text-center">
      <div class="pagination">
        <%= will_paginate @photos %>
      </div>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<%= image_tag(@photo.ig_permalink) %>